data= read.table("household_power_consumption.txt", header=T, sep=";", dec=".",stringsAsFactors=FALSE)
dim(data)
sub= data[data$Date %in% c("1/2/2007","2/2/2007"),]
dim(sub)
class(sub$Global_active_power)
power=as.numeric(sub$Global_active_power)
dates = strptime(paste(sub$Date, sub$Time, sep=" "), "%d %m %Y %H:%M:%S")
png("assignmnent//plot2.png", width=480, height=480)
plot(dates, power, type="l", xlab= "   ", ylab="Global Active Power(kilowatts)")
dev.off()