data= read.table("household_power_consumption.txt", header=T, sep=";", dec=".",stringsAsFactors=FALSE)
dim(data)
sub= data[data$Date %in% c("1/2/2007","2/2/2007"),]
dim(sub)
class(sub$Global_active_power)
power=as.numeric(sub$Global_active_power)
dates = strptime(paste(sub$Date, sub$Time, sep=" "), "%d %m %Y %H:%M:%S")
class(sub$Sub_metering_1)
meter1=as.numeric(sub$Sub_metering_1)
meter2=as.numeric(sub$Sub_metering_2)
meter3=as.numeric(sub$Sub_metering_3)
class(sub$Voltage)
volt = as.numeric(sub$Voltage)
class(sub$Global_reactive_power)
Reactive = as.numeric(sub$Global_reactive_power)
head(Reactive)
plot(dates, Reactive, type="l", xlab="datetime",ylab="Global_Reactive_Power")
png("E://data_scientiest toolbar//exploratory data analysis//assignmnent1//plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(dates, power, type="l", xlab="", ylab="Global Active Power")
plot(dates, volt,type="l", xlab="", ylab="Voltage")
plot(dates, meter1, type="l", xlab="", ylab="Energy Sub Metering")
lines(dates, meter2, type="l")
lines(dates, meter2, type="l", col="red")
lines(dates, meter3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty=1)
dev.off()