data= read.table("household_power_consumption.txt", header=T, sep=";", dec=".",stringsAsFactors=FALSE)
dim(data)
sub= data[data$Date %in% c("1/2/2007","2/2/2007"),]
dim(sub)
class(sub$Global_active_power)
power=as.numeric(sub$Global_active_power)
dates = strptime(paste(sub$Date, sub$Time, sep=" "), "%d %m %Y %H:%M:%S")
class(sub$Sub_metering_1)
meter1=as.numeric(sub$Sub_metering_1)
meter2=as.numeric(sub$Sub_metering_2)
meter3=as.numeric(sub$Sub_metering_3)
png("assignmnent//plot3.png", width=480, height=480)
plot(dates,meter1,col="black", type="l", ylab="Energy Sub Metering", xlab="")
lines(dates, meter3, col="blue", type="l")
lines(dates, meter2, col="red", type="l")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty=1)
dev.off()